system:
  type: Quadrotor_NL
  feedback: FullState
  controller: natural_none_gates
  dagger: false

analysis:
  method: carv
  kmax: 10
  initial_state_range: "[[2.5, 3.0], [-0.25, 0.25]]"
  t_max: 5
  estimate_runtime: false
  estimate_error: false
  estimate_memory: false

visualization:
  save_plot: false
  show_plot: true
  make_animation: false
  plot_dims: [0, 1]
  plot_aspect: auto
  plot_lims: null
